### ISSUE TITLE
Chests don't always close

### ISSUE THREAD

**Issue by SlothInTheBroth** [Reoseah/reinstorage#1]
Chests when exited out of don't always close their lid

**Comment by Reoseah** [comment]
Yes, they do that randomly with one player and always with two or more players. 

fixed in https://github.com/Reoseah/reinstorage/commit/b088a723daa288dba3d18ef31e471cc5918ad33d, will be on Curse with 1.1 version

**Comment by Reoseah** [comment]
https://minecraft.curseforge.com/projects/reinforced-storage/files v1.1 released
